### ISSUE TITLE
generate(ClientTokenRequest request) accepting "null" value for customerId

### ISSUE THREAD

**Issue by silentsnooc** [braintree/braintree_java#44] opened 2016-08-07 16:40 UTC
I am not entirely sure why this is the case but

```java
ClientTokenRequest clientTokenRequest = new ClientTokenRequest()
		.customerId(null);

return BT.clientToken().generate(clientTokenRequest);
``` 

does create a server token. I did not test if I can use this token actually but shouldn't there be an error message saying that this user does not exist in my vault?

**Comment by mtmarsh3** [comment] 2016-08-08 20:07
Hi Silentsnooc,

Thanks for reaching out, we are currently looking into this.

**Comment by mtmarsh3** [comment] 2016-08-09 14:15
I was not able to reproduce your issue, is `BT` representing a `BraintreeGateway`?
When I tried calling `generate(null)`, I received a `NullPointerException` and did not generate a server token due to the line below, which is within [`ClientTokenGateway`](https://github.com/braintree/braintree_java/blob/d2f00dfe725db07ef32810e42a11652f612d3516/src/main/java/com/braintreegateway/ClientTokenGateway.java#L47).


Could you tell me what version of the client library you are using? I would also recommend reaching out to support at: support@braintreepayments.com for further help.

**Comment by silentsnooc** [comment] 2016-08-09 19:23
@mtmarsh3 Hi!

I just saw that I modified the code wrong! I set the request object `null` in the code. I've edited my original post from

```java
return BT.clientToken().generate(null);
``` 

to 
```java
ClientTokenRequest clientTokenRequest = new ClientTokenRequest()
        .customerId(null);

return BT.clientToken().generate(clientTokenRequest);
``` 

I've just been running this and I'm receiving a token that way. Is this intended? The version I'm using is

```xml
<dependency>
    <groupId>com.braintreepayments.gateway</groupId>
    <artifactId>braintree-java</artifactId>
    <version>2.65.0</version>
</dependency>
```

**Comment by mtmarsh3** [comment] 2016-08-11 21:58
Thanks for the update. This is part of the intended behavior, as generating a `ClientTokenRequest`  without a specified `customerId` should operate the same in both the `ClientTokenRequest()` and `ClientTokenRequest().customerId(null)` constructors.

**Comment by pblesi** [comment] 2016-08-12 15:28
I am going to close this issue. If you have further questions, feel free to reopen this issue.

**Closed by pblesi** 2016-08-12 15:28 UTC

**Comment by Thkasis** [comment] 2019-02-18 18:51
Since the nature of problem is the same I add it under this thread. Trying to generate token using Node.js, giving an arbitrary string as customerID that doesn't get captured in err and rather the response comes with an error message object like below. I'm using Braintree 2.15.0 & Node.js.

gateway.clientToken.generate({
  customerId: "someRandomText"
}, function (err, response) {
      //err is null and rather response is an object like below
});

Example response : 
RESPONSE RECEIVED FROM FUNCTION: 200, {
  "result": {
    "token": {
      "errors": {
        "validationErrors": {},
        "errorCollections": {
          "clientToken": {
            "validationErrors": {
              "customerId": [
                {
                  "attribute": "customer_id",
                  "code": "92804",
                  "message": "Customer specified by customer_id does not exist"
                }
              ]
            },
            "errorCollections": {}
          }
        }
      },
      "params": "",
      "message": "Customer specified by customer_id does not exist",
      "success": false
    }
  }
}

Shouldn't that error be captured in err instead of response?

**Comment by crookedneighbor** [comment] 2019-02-19 14:49
the `err` param is reserved for issues with the request itself. IE, if the Braintree Gateway was to return a 500 or if the underlying API route you were attempting to hit did not exist and returned a 404.

All 422 errors are returned as results where `success` is `false`, which is what is happening here. You're hitting the client token generation route, which does exist, but using a customer id that does not, which triggers a validation error.

Please contact our support team if you have additional questions about this: https://help.braintreepayments.com/
