### ISSUE TITLE
JSON license issue

### ISSUE THREAD

**Issue by lburgazzoli** [braintree/braintree_java#59] opened 2018-01-23 12:50 UTC
From version 2.68.0, the sdk includes org.json and its license is not more compatible with Apache Software License (see https://www.apache.org/legal/resolved.html#json) so it is not possible to use this sdk in projects such apache-camel.

Is there any chance to switch to a different json framework ? (i.e. https://github.com/FasterXML/jackson-jr)

**Comment by oscerd** [comment] 2018-01-23 12:55
duplicate #58

**Comment by crookedneighbor** [comment] 2018-01-23 14:23
Closing this as a duplicate of #58

**Closed by crookedneighbor** 2018-01-23 14:23 UTC
